version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: telegamez_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegamez
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    container_name: telegamez_web
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/telegamez
      PORT: 3100
      NODE_ENV: production
    ports:
      - "127.0.0.1:3100:3100"
    restart: unless-stopped

volumes:
  pgdata:

